/**
 * Prints `CREATE TABLE IF NOT EXISTS` SQL for every collection in the shared
 * CMS registry (`@three-acts/cms-schema`), using the exact same column
 * mapping the API's `SupabaseDataStore` reads and writes. Point any Postgres
 * database at this schema and the CMS backend works against it.
 *
 * Usage: `npm run schema:sql -w @three-acts/api` (prints to stdout; pipe to a
 * file or `psql` as needed). Review before running — adjust types,
 * constraints, and the RLS example to your needs.
 */
import { collectionRegistry, columnForField, systemColumnsFor, type CmsCollection, type CmsField } from "@three-acts/cms-schema";

function sqlColumnType(field: CmsField): string {
  switch (field.type) {
    case "number":
      return "numeric";
    case "boolean":
      return "boolean";
    case "datetime":
      return "timestamptz";
    // text/textarea/slug/select/asset/readonly all store plain text.
    default:
      return "text";
  }
}

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function tableSql(collection: CmsCollection): string {
  const sys = systemColumnsFor(collection);

  const columnLines = [
    `${quoteIdent(sys.id)} uuid primary key default gen_random_uuid()`,
    `${quoteIdent(sys.publishStatus)} text not null default 'not_published'`,
    `${quoteIdent(sys.createdAt)} timestamptz not null default now()`,
    `${quoteIdent(sys.modifiedAt)} timestamptz not null default now()`,
    ...collection.fields.map((field) => `${quoteIdent(columnForField(collection, field))} ${sqlColumnType(field)}`)
  ];

  const table = quoteIdent(collection.tableName);
  const triggerFn = quoteIdent(`set_${collection.tableName}_${sys.modifiedAt}`);
  const trigger = quoteIdent(`trg_${collection.tableName}_${sys.modifiedAt}`);

  return [
    `-- ${collection.label} (${collection.id})`,
    `create table if not exists ${table} (`,
    columnLines.map((line) => `  ${line}`).join(",\n"),
    `);`,
    ``,
    `create or replace function ${triggerFn}()`,
    `returns trigger as $$`,
    `begin`,
    `  new.${quoteIdent(sys.modifiedAt)} = now();`,
    `  return new;`,
    `end;`,
    `$$ language plpgsql;`,
    ``,
    `drop trigger if exists ${trigger} on ${table};`,
    `create trigger ${trigger}`,
    `before update on ${table}`,
    `for each row`,
    `execute function ${triggerFn}();`
  ].join("\n");
}

function printSchema(): void {
  const header = [
    "-- Generated by `npm run schema:sql -w @three-acts/api` from packages/cms-schema/src/registry.ts.",
    "-- Review before running: adjust column types/constraints/RLS to your needs.",
    "-- gen_random_uuid() needs pgcrypto on Postgres < 13:",
    "--   create extension if not exists pgcrypto;",
    ""
  ].join("\n");

  const tables = collectionRegistry.map(tableSql).join("\n\n");

  const rlsExample = [
    "",
    "-- Example RLS policy (not enabled by default). The API always connects",
    "-- with the Supabase service-role key, which bypasses RLS, so this only",
    "-- matters if these tables are also queried directly with the anon/public",
    "-- key (e.g. from apps/web). Adjust the role/condition to your auth model:",
    "--",
    "-- alter table launch_pages enable row level security;",
    "-- create policy \"public can read published rows\" on launch_pages",
    "--   for select",
    "--   using (publish_status = 'published');",
    ""
  ].join("\n");

  console.log(`${header}\n${tables}\n${rlsExample}`);
}

printSchema();
